version: "2.0"
services:
  postgres:
    container_name: postgres
    image: postgres:13.3
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "sad"
      POSTGRES_USER: "sad"
      POSTGRES_PASSWORD: "sadpasswd"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgres/sql/:/docker-entrypoint-initdb.d
      - ./postgres/data/:/var/lib/postgresql/data/
    restart: unless-stopped
    networks:
      - sad

  web-iface:
    container_name: frontend
    image: nginx:stable
    environment:
      - TZ=Europe/Moscow
      - VERSION
    depends_on:
      - php
      - postgres
    ports:
      - 80:80
    volumes:
      - ./conf.d/sad:/etc/nginx/conf.d/default.conf
      - ./conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./app:/var/www/sad
    networks:
      - sad
  php:
    container_name: backend
    build:
      context: ./php
    depends_on:
      - postgres
    environment:
      - TZ=Europe/Moscow
      - VERSION
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./app:/var/www/sad
      - ./app/keys/:/var/www/sad/keys
      - ./app/documents/:/var/www/sad/documents
    networks:
      - sad

  

networks:
  sad: